# Generated by Django 5.1.6 on 2025-03-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='name',
            field=models.CharField(max_length=2955),
        ),
    ]
