# Generated by Django 5.1.6 on 2025-03-02 01:16

import crud.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_sensor_system_hydroponicsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hydroponic_system',
            field=models.ForeignKey(default=crud.models.get_default_system, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='crud.hydroponicsystem'),
        ),
    ]
